[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "Wartungsplan"
version = "1.0rc3"
description = "Manage recurring tasks in ical"
readme = "README.md"
requires-python = ">=3.10,<3.14"
license = {text = "GPLv3"}
authors = [
    {name = "Felix Bauer", email = "felix.bauer@atos.net"},
]
maintainers = [
    {name = "Felix Bauer", email = "felix.bauer@eviden.com"},
    {name = "Christian Habrom", email = "christian.habrom@eviden.com"},
]

dependencies = [
        "icalendar==7.0.3",
        "python-dateutil==2.9.0",
        "recurring-ical-events==3.8.1",
        "requests==2.32.5",
        "importlib_metadata==9.0.0",
]

[project.optional-dependencies]
otrs = [ "pyotrs==1.5.2" ]
exchange = [ "exchangelib==5.6.0" ]

[project.urls]
repository = "https://github.com/science-computing/wartungsplan"

[project.scripts]
Wartungsplan = "Wartungsplan:main"
addEventToIcal = "addEventToIcal:main"
downloadExchange = "downloadExchange:main"
